const initialState = {
  grades: [
    { id: "XyDE", title: "Common" },
    { id: "3XE9", title: "Rare" },
    { id: "fod3", title: "Epic" },
    { id: "BB4h", title: "Legendary" },
  ],
  races: [
    { id: "HVSp", title: "Human" },
    { id: "u2TP", title: "Wild" },
    { id: "z18Y", title: "Sacred" },
    { id: "T1WD", title: "Dark" },
  ],
  troops: [
    {
      grade: "XyDE",
      id: "1DG4",
      image: "/img/aow-troops/archers.png",
      name: "Archers",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "XyDE",
      id: "KMfr",
      image: "/img/aow-troops/infantry.png",
      name: "Infantry",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "XyDE",
      id: "ia3F",
      image: "/img/aow-troops/ironguards.png",
      name: "Iron Guards",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "XyDE",
      id: "aHk2",
      image: "/img/aow-troops/bomber.png",
      name: "Bomber",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "XyDE",
      id: "sYMV",
      image: "/img/aow-troops/catapult.png",
      name: "Catapult",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "XyDE",
      id: "duED",
      image: "/img/aow-troops/helljailers.png",
      name: "Hell Jailers",
      race: "T1WD",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "xKS4",
      image: "/img/aow-troops/firemage.png",
      name: "Fire Mage",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "3XE9",
      id: "x68d",
      image: "/img/aow-troops/bandits.png",
      name: "Bandits",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "TifV",
      image: "/img/aow-troops/ogrewarrior.png",
      name: "Ogre Warrior",
      race: "u2TP",
      count: 1,
    },
    {
      grade: "3XE9",
      id: "u3vo",
      image: "/img/aow-troops/ghostassassins.png",
      name: "Ghost Assassin",
      race: "T1WD",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "VYNk",
      image: "/img/aow-troops/magicapprentice.png",
      name: "Magic Apprentice",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "jE0t",
      image: "/img/aow-troops/vikingwarrior.png",
      name: "Viking Warrior",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "3XE9",
      id: "RwaZ",
      image: "/img/aow-troops/icemage.png",
      name: "Ice Mage",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "3XE9",
      id: "X5LF",
      image: "/img/aow-troops/scholar.png",
      name: "Scholar",
      race: "z18Y",
      count: 1,
    },
    {
      grade: "3XE9",
      id: "KSiE",
      image: "/img/aow-troops/inquisitor.png",
      name: "Inquisitor",
      race: "z18Y",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "ELzN",
      image: "/img/aow-troops/undeadsoldier.png",
      name: "Undead Soldier",
      race: "T1WD",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "YVcP",
      image: "/img/aow-troops/harbingeroffire.png",
      name: "Harbinger of Fire",
      race: "z18Y",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "od7I",
      image: "/img/aow-troops/paladin.png",
      name: "Paladin",
      race: "z18Y",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "JmMK",
      image: "/img/aow-troops/ballista.png",
      name: "Ballista",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "3XE9",
      id: "qap2",
      image: "/img/aow-troops/goblikazes.png",
      name: "Goblikazes",
      race: "u2TP",
      count: 9,
    },
    {
      grade: "3XE9",
      id: "cHYq",
      image: "/img/aow-troops/cactus.png",
      name: "Cactuses",
      race: "u2TP",
      count: 9,
    },
    {
      grade: "fod3",
      id: "VOFU",
      image: "/img/aow-troops/necromancer.png",
      name: "Necromancer",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "fod3",
      id: "cMlE",
      image: "/img/aow-troops/pilgrims.png",
      name: "Pilgrims",
      race: "z18Y",
      count: 9,
    },
    {
      grade: "fod3",
      id: "uvZH",
      image: "/img/aow-troops/pumpkinguard.png",
      name: "Pumpkin Guard",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "fod3",
      id: "drTp",
      image: "/img/aow-troops/darkwitch.png",
      name: "Dark Witch",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "fod3",
      id: "qZFw",
      image: "/img/aow-troops/yasha.png",
      name: "Yasha",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "fod3",
      id: "bIYJ",
      image: "/img/aow-troops/priestmage.png",
      name: "Priest Mage",
      race: "z18Y",
      count: 1,
    },
    {
      grade: "fod3",
      id: "Xbyh",
      image: "/img/aow-troops/soulhunter.png",
      name: "Soul Hunter",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "fod3",
      id: "ZMFE",
      image: "/img/aow-troops/templarknight.png",
      name: "Templar Knight",
      race: "z18Y",
      count: 1,
    },
    {
      grade: "fod3",
      id: "yivK",
      image: "/img/aow-troops/peltasts.png",
      name: "Peltasts",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "fod3",
      id: "uuZv",
      image: "/img/aow-troops/brawlers.png",
      name: "Brawlers",
      race: "HVSp",
      count: 9,
    },
    {
      grade: "fod3",
      id: "EwWV",
      image: "/img/aow-troops/tauruswitcher.png",
      name: "Taurus Witcher",
      race: "u2TP",
      count: 9,
    },
    {
      grade: "fod3",
      id: "OL9j",
      image: "/img/aow-troops/voodoodolls.png",
      name: "Voodoo Dolls",
      race: "T1WD",
      count: 9,
    },
    {
      grade: "BB4h",
      id: "hBpl",
      image: "/img/aow-troops/demon.png",
      name: "Demon",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "TK2L",
      image: "/img/aow-troops/beastmaster.png",
      name: "Beast Master",
      race: "z18Y",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "7FVE",
      image: "/img/aow-troops/witchcrafttotem.png",
      name: "Witchcraft Totem",
      race: "u2TP",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "BMEK",
      image: "/img/aow-troops/meteorgolem.png",
      name: "Meteor Golem",
      race: "T1WD",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "BHYu",
      image: "/img/aow-troops/stonegolem.png",
      name: "Stone Golem",
      race: "u2TP",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "GOiK",
      image: "/img/aow-troops/frostarchers.png",
      name: "Frost Archers",
      race: "z18Y",
      count: 9,
    },
    {
      grade: "BB4h",
      id: "zX4n",
      image: "/img/aow-troops/sacredswordsman.png",
      name: "Sacred Swordsman",
      race: "z18Y",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "MIgO",
      image: "/img/aow-troops/rhinoknight.png",
      name: "Rhino Knight",
      race: "u2TP",
      count: 1,
    },
    {
      grade: "BB4h",
      id: "IKOP",
      image: "/img/aow-troops/pharaoh.png",
      name: "Pharaoh",
      race: "HVSp",
      count: 1,
    },
    {
      grade: "fod3",
      id: "3eVk",
      image: "/img/aow-troops/nun.png",
      name: "Nun",
      race: "HVSp",
      count: 9,
    },
  ],
  board: {
    squares: 49,
    maxLevel: 9,
  },
};

export default initialState;
